### ISSUE TITLE
ImportError: DLL load failed while importing decrypt: The specified module could not be found.

### ISSUE THREAD

**Issue by moux23333** [acezx-programer/H-SR-cutscene-extractor#1]
Traceback (most recent call last):
  File "E:\H-SR-cutscene-extractor-main\main.py", line 9, in <module>
    from usm import demux
  File "E:\H-SR-cutscene-extractor-main\usm\demux.py", line 14, in <module>
    from decrypt import VideoDecrypter
ImportError: DLL load failed while importing decrypt: The specified module could not be found.

Python Version:3.12.0 (32-Bit) Windows:Windows 11 22H2 22621.2361
i tried 64-Bit python but i got different error:

Traceback (most recent call last):
   File "E:\H-SR-cutscene-extractor-main\main.py", line 9, in <module>
     from usm import demux
   File "E:\H-SR-cutscene-extractor-main\usm\demux.py", line 14, in <module>
     from decrypt import VideoDecrypter
ImportError: DLL load failed while importing decrypt: %1 is not a valid Win32 application.

Python 3.11 is not work too and same error

**Comment by acezx-programer** [comment]
sorry, i havent updated this to a while. Heres the fix:

1. download [PyCriUsm](https://github.com/BUnipendix/PyCriUsm)
2. build using `python setup.py build_ext --inplace`
3. rename the build to decrypt.pyd and replace the dll in USM folder
