### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_decrypt)

### ISSUE THREAD

**Issue by CuteCat233** [acezx-programer/H-SR-cutscene-extractor#11]
Traceback (most recent call last):
  File "D:\Programs\H-SR-cutscene-extractor-main\main.py", line 9, in <module>
    from usm import demux
  File "D:\Programs\H-SR-cutscene-extractor-main\usm\demux.py", line 9, in <module>
    from .decrypt import VideoDecrypter
ImportError: dynamic module does not define module export function (PyInit_decrypt)

Perhaps there is no ”VideoDecrypter“ in the latest pycriusm? (There's no problem using pycriusm alone. And I looked at the demux.py of pycriusm and found that there was no VideoDecrypter)

Or it could be my problem

**Comment by CuteCat233** [comment]
And if I copy all the files to the USM folder.

Traceback (most recent call last):
  File "D:\Programs\H-SR-cutscene-extractor-main\main.py", line 182, in <module>
    run()
  File "D:\Programs\H-SR-cutscene-extractor-main\main.py", line 93, in run
    ext = **extvid(inp)**
  File "D:\Programs\H-SR-cutscene-extractor-main\main.py", line 59, in extvid
    a = **demux.UsmDemuxer**(usm_path)
AttributeError: 'function' object has no attribute 'UsmDemuxer'

**Comment by BUnipendix** [comment]
我的PyCriUsm库里的代码之前大修，接口全换了，要改一下这个库的代码才能跑

**Comment by CuteCat233** [comment]
Traceback (most recent call last):
  File "D:\Programs\H-SR-cutscene-extractor-main\main.py", line 180, in <module>
    run()
  File "D:\Programs\H-SR-cutscene-extractor-main\main.py", line 91, in run
    ext = extvid(inp)
          ^^^^^^^^^^^
  File "D:\Programs\H-SR-cutscene-extractor-main\main.py", line 59, in extvid
    return demux.extract_usm(usm_path, output_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: extract_usm() missing 1 required positional argument: 'is_async'

在括号内加上is_async = True 后FFMPEG报错：

Input #0, ivf, from './output\CS_Chap01_Act210_f.ivf':
  Duration: 00:00:28.67, start: 0.000000, bitrate: 7155 kb/s
  Stream #0:0: Video: vp9 (Profile 0) (VP90 / 0x30395056), yuv420p(tv, smpte170m/unknown/unknown), 2560x1440, 30 tbr, 30 tbn
[out#0/mp4 @ 00000258590f7300] Error opening output ./output/converted/CS_Chap01_Act210_f.mp4: No such file or directory
Error opening output file ./output/converted/CS_Chap01_Act210_f.mp4.
Error opening output files: No such file or directory

[adx @ 000001a986ab2b00] Format adx detected only with low score of 1, misdetection possible!
[in#0 @ 000001a986a70f40] Error opening input: Invalid data found when processing input
Error opening input file ./output\CS_Chap01_Act210_f_0.adx.
Error opening input files: Invalid data found when processing input

**Comment by CuteCat233** [comment]
在output文件夹里新建“comverted”与"final"文件后**大概率不会报错**。但最终的视频无法播放。

FFMPEG运行中报错：
[ivf @ 000001602eb6e840] Packet corrupt (stream = 0, dts = NOPTS).
[in#0/ivf @ 000001602eb9aa80] corrupt input packet in stream 0
DTS 1156600068913106688, next:600000 st:0 invalid dropping
PTS 1156600068913106688, next:600000 invalid dropping st:0
[vp9 @ 000001602ec00500] Invalid frame marker
[vist#0:0/vp9 @ 000001602ebbc9c0] [dec:vp9 @ 000001602eb73180] Decoding error: Invalid data found when processing input

**Comment by CuteCat233** [comment]
补一张图（CS_Act410_f_3_final) ![image](https://github.com/acezx-programer/H-SR-cutscene-extractor/assets/126493293/37134f67-bd96-4d6f-b316-dc427cef350a)

**Comment by acezx-programer** [comment]
will try to fix/update to match [BUnipendix](https://github.com/BUnipendix)'s repository, im currently busy, thanks

**Comment by BUnipendix** [comment]
> Traceback (most recent call last):
>   File "D:\Programs\H-SR-cutscene-extractor-main\main.py", line 180, in <module>
>     run()
>   File "D:\Programs\H-SR-cutscene-extractor-main\main.py", line 91, in run
>     ext = extvid(inp)
>           ^^^^^^^^^^^
>   File "D:\Programs\H-SR-cutscene-extractor-main\main.py", line 59, in extvid
>     return demux.extract_usm(usm_path, output_dir)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: extract_usm() missing 1 required positional argument: 'is_async'
> 
> 在括号内加上is_async = True 后FFMPEG报错：
> 
> Input #0, ivf, from './output\CS_Chap01_Act210_f.ivf':
>   Duration: 00:00:28.67, start: 0.000000, bitrate: 7155 kb/s
>   Stream #0:0: Video: vp9 (Profile 0) (VP90 / 0x30395056), yuv420p(tv, smpte170m/unknown/unknown), 2560x1440, 30 tbr, 30 tbn
> [out#0/mp4 @ 00000258590f7300] Error opening output ./output/converted/CS_Chap01_Act210_f.mp4: No such file or directory
> Error opening output file ./output/converted/CS_Chap01_Act210_f.mp4.
> Error opening output files: No such file or directory
> 
> [adx @ 000001a986ab2b00] Format adx detected only with low score of 1, misdetection possible!
> [in#0 @ 000001a986a70f40] Error opening input: Invalid data found when processing input
> Error opening input file ./output\CS_Chap01_Act210_f_0.adx.
> Error opening input files: Invalid data found when processing input

我的失误，我忘记给is_async参数加默认值False，请将is_async 设为False

My mistake, I forgot to add the default value False to the `is_async` argument
please set is_async to False

**Comment by CuteCat233** [comment]
> l

改为False后：
Traceback (most recent call last):
  File "D:\Programs\H-SR-cutscene-extractor-main\main.py", line 180, in <module>
    run()
  File "D:\Programs\H-SR-cutscene-extractor-main\main.py", line 91, in run
    ext = **extvid(inp)**

  File "D:\Programs\H-SR-cutscene-extractor-main\main.py", line 59, in extvid
    return demux.extract_usm(usm_path, output_dir, is_async = False)

  File "D:\Programs\H-SR-cutscene-extractor-main\usm\demux.py", line 29, in extract_usm
    return **demux(video_path, output, *key_args, is_async, **kwargs)**

  File "D:\Programs\H-SR-cutscene-extractor-main\usm\demux.py", line 201, in demux
    return **wait()**

  File "D:\Programs\H-SR-cutscene-extractor-main\usm\demux.py", line 195, in wait
    return _coro_wait()_**[1]**

IndexError: list index out of range

**Comment by BUnipendix** [comment]
啊，我代码有问题，这个得等我有时间修了（只测了async模式因为test的代码只支持async，没时间写同步模式）
