### ISSUE TITLE
Error running start.bat

### ISSUE THREAD

**Issue by Tsaleem123** [acezx-programer/H-SR-cutscene-extractor#7]
Looks like every step worked except when I import a usm file. Then I get the following error.

Traceback (most recent call last):
  File "C:\Users\Talha\OneDrive\Desktop\H-SR-cutscene-extractor-main\main.py", line 182, in <module>
    run()
  File "C:\Users\Talha\OneDrive\Desktop\H-SR-cutscene-extractor-main\main.py", line 93, in run
    ext = extvid(inp)
          ^^^^^^^^^^^
  File "C:\Users\Talha\OneDrive\Desktop\H-SR-cutscene-extractor-main\main.py", line 60, in extvid
    video_name, audio_names = a.export(output_dir)
                              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Talha\OneDrive\Desktop\H-SR-cutscene-extractor-main\usm\demux.py", line 128, in export
    return writing_thread.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Talha\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Talha\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Talha\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Talha\OneDrive\Desktop\H-SR-cutscene-extractor-main\usm\demux.py", line 164, in _writing_loop
    video_output = FileIO(video, 'wb')
                   ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: WindowsPath('output/CS_ChapLoop03_Act0060.ivf')

**Comment by acezx-programer** [comment]
please make sure that youve created a folder named "output" in the directory
