### ISSUE TITLE
TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by aether1010** [acezx-programer/H-SR-cutscene-extractor#8]
Traceback (most recent call last):
  File "C:\Users\usr\Desktop\HSR-cutscene-extractor\main.py", line 182, in <module>
    run()
  File "C:\Users\usr\Desktop\HSR-cutscene-extractor\main.py", line 93, in run
    ext = extvid(inp)
          ^^^^^^^^^^^
  File "C:\Users\usr\Desktop\HSR-cutscene-extractor\main.py", line 59, in extvid
    a = demux.UsmDemuxer(usm_path)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Desktop\HSR-cutscene-extractor\usm\demux.py", line 79, in __init__
    tmp_key = key_map.get(video_path.stem, None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\collections\__init__.py", line 1017, in get
    return self[key] if key in self else default
                        ^^^^^^^^^^^
  File "C:\Python312\Lib\collections\__init__.py", line 1029, in __contains__
    return any(key in m for m in self.maps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\collections\__init__.py", line 1029, in <genexpr>
    return any(key in m for m in self.maps)
               ^^^^^^^^
TypeError: argument of type 'int' is not iterable

Python Version: Python 3.12.2

After cmd (py main.py -e) and I chose the files of the cutscene, it came out this Error
How could I fix this? Is the version of python wrong?

**Comment by acezx-programer** [comment]
this error is because you havent updated the keys, each cutscene has a different "key" that is used to decrypt the video, the keys that are used in this repo are outdated and does not support version hsr 2.0, to get new keys you have to Reverse engineer the keys using a proto sniffer, but of course you will also have to deobfuscate the protos first. a lot of work.
